version: '3'

services:
  app:
    build: ./docker/app
    depends_on:
      - db
    volumes:
      - .:/var/www/html:cached

  web:
    image: nginx
    ports:
      - 8000:80
    depends_on:
      - app
    volumes:
      - .:/var/www/html:cached
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf

  db:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - laravel-db-data:/var/lib/mysql

  nuxt:
    build: ./docker/nuxt
    tty: true
    command: yarn dev
    volumes:
        - ./frontend:/var/www/html/frontend
    ports:
      - "3000:3000"

volumes:
  laravel-db-data:
    driver: local
